"""Add image_url and price fields

Revision ID: 403c9831d3cb
Revises: b7e796145dd4
Create Date: 2024-12-11 11:31:22.451453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403c9831d3cb'
down_revision = 'b7e796145dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('activity', sa.Column('price', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'price')
    op.drop_column('activity', 'image_url')
    # ### end Alembic commands ###
